name: Compile and Deploy

on:
  push:
    branches: 
      - main
    paths:
      - 'Homework/**'

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            Homework/code1.tex
            Homework/code2.tex
            Homework/code3.tex
            Homework/code4.tex
            Homework/code5.tex
            Homework/hw1.tex
            Homework/hw2.tex
            Homework/hw3.tex
            Homework/hw4.tex
            Homework/hw5.tex
          latexmk_use_xelatex: false

      - name: Move PDFs to dist folder
        run: |
          mkdir -p files/
          mv *.pdf files/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
